### ISSUE TITLE
Trying to follow the Quickstart Guide and complains some errors( ERROR -- : fsevent: running worker failed: wrong number of arguments (given 2, expected 1):)

### ISSUE THREAD

**Issue by romenigld** [wearefine/fae#255]
I'm trying to following the tutorial Quickstart Guide on Documentation and in when I try to do: 
`rails g fae:install`
Was complained an error on migration and was needed to put on every migration for example this:
class AddUserTable `< ActiveRecord::Migration[5.1]`
And then was generated the migrations, but when try the migration for `CreateFaeTextFields`, was complained another error:
20170629134829 CreateFaeTextFields: migrating ==============================
```
-- create_table(:fae_text_fields)
E, [2017-06-29T15:58:19.500905 #19207] ERROR -- : fsevent: running worker failed: wrong number of arguments (given 2, expected 1):
```

here is the complete log for the terminal:
```

rails g fae:install
Running via Spring preloader in process 19202
         run  bundle install from "."
Using rake 12.0.0
Using concurrent-ruby 1.0.5
Using i18n 0.8.4
Using minitest 5.10.2
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubi 1.6.1
Using mini_portile2 2.2.0
Using rack 2.0.3
Using nio4r 2.1.0
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 8.0.0
Using public_suffix 2.0.5
Using bcrypt 3.1.11
Using bindex 0.5.0
Using browser 0.8.0
Using byebug 9.0.6
Using json 2.1.0
Using ffi 1.9.18
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using method_source 0.8.2
Using thor 0.19.4
Using orm_adapter 0.5.0
Using bundler 1.14.6
Using remotipart 1.3.1
Using rmagick 2.13.4
Using sass 3.4.24
Using tilt 2.0.7
Using temple 0.8.0
Using multi_json 1.12.1
Using rb-fsevent 0.10.1
Using ruby_dep 1.5.0
Using puma 3.9.1
Using rubyzip 1.2.1
Using sqlite3 1.3.13
Using turbolinks-source 5.0.3
Using tzinfo 1.2.3
Using nokogiri 1.8.0
Using rack-test 0.6.3
Using warden 1.2.7
Using sprockets 3.7.1
Using websocket-driver 0.6.5
Using mime-types 3.1
Using addressable 2.5.1
Using childprocess 0.7.1
Using rb-inotify 0.9.10
Using coffee-script 2.4.1
Using uglifier 3.2.0
Using slim 3.0.8
Using turbolinks 5.0.1
Using activesupport 5.1.2
Using loofah 2.0.3
Using xpath 2.1.0
Using mail 2.6.6
Using selenium-webdriver 3.4.3
Using listen 3.1.5
Using rails-dom-testing 2.0.3
Using globalid 0.4.0
Using activemodel 5.1.2
Using jbuilder 2.7.0
Using spring 2.0.2
Using rails-html-sanitizer 1.0.3
Using capybara 2.14.4
Using activejob 5.1.2
Using activerecord 5.1.2
Using carrierwave 0.10.0
Using spring-watcher-listen 2.0.1
Using actionview 5.1.2
Using acts_as_list 0.9.5
Using actionpack 5.1.2
Using actioncable 5.1.2
Using actionmailer 5.1.2
Using railties 5.1.2
Using sprockets-rails 3.2.0
Using simple_form 3.5.0
Using kaminari 0.17.0
Using coffee-rails 4.2.2
Using responders 2.4.0
Using jquery-rails 4.3.1
Using jquery-ui-rails 4.2.1
Using web-console 3.5.1
Using rails 5.1.2
Using sass-rails 5.0.6
Using devise 4.3.0
Using judge 2.1.1
Using judge-simple_form 1.0.0
Using fae-rails 1.5.1
Bundle complete! 16 Gemfile dependencies, 89 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
      insert  config/routes.rb
   identical  lib/tasks/fae_tasks.rake
   identical  app/assets/stylesheets/fae.scss
   identical  app/assets/javascripts/fae.js
   identical  app/models/concerns/fae/navigation_concern.rb
   identical  app/models/concerns/fae/authorization_concern.rb
    conflict  config/initializers/fae.rb
Overwrite /Users/romenigld/workspace/tutorials/fae_cms/fae/config/initializers/fae.rb? (enter "h" for help) [Ynaqdh] a
       force  config/initializers/fae.rb
      insert  config/initializers/fae.rb
   identical  config/initializers/judge.rb
        rake  fae:install:migrations
        rake  db:migrate
== 20170629134823 CreateFaeRoles: migrating ===================================
-- create_table(:fae_roles)
   -> 0.0014s
== 20170629134823 CreateFaeRoles: migrated (0.0015s) ==========================

== 20170629134824 CreateFaeImagesTable: migrating =============================
-- create_table(:fae_images)
   -> 0.0036s
== 20170629134824 CreateFaeImagesTable: migrated (0.0037s) ====================

== 20170629134825 CreateFaeOptions: migrating =================================
-- create_table(:fae_options)
   -> 0.0009s
-- add_index(:fae_options, :singleton_guard, {:unique=>true})
   -> 0.0009s
== 20170629134825 CreateFaeOptions: migrated (0.0019s) ========================

== 20170629134826 CreateFaeFiles: migrating ===================================
-- create_table(:fae_files)
   -> 0.0051s
== 20170629134826 CreateFaeFiles: migrated (0.0052s) ==========================

== 20170629134827 CreateFaeTextAreas: migrating ===============================
-- create_table(:fae_text_areas)
   -> 0.0241s
== 20170629134827 CreateFaeTextAreas: migrated (0.0242s) ======================

== 20170629134828 CreateFaePages: migrating ===================================
-- create_table(:fae_static_pages)
   -> 0.0036s
== 20170629134828 CreateFaePages: migrated (0.0038s) ==========================

== 20170629134829 CreateFaeTextFields: migrating ==============================
-- create_table(:fae_text_fields)
E, [2017-06-29T15:58:19.500905 #19207] ERROR -- : fsevent: running worker failed: wrong number of arguments (given 2, expected 1):/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/base.rb:41:in `block (2 levels) in configure'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/rb-fsevent-0.10.1/lib/rb-fsevent/fsevent.rb:75:in `run'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:71:in `_run_worker'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:55:in `_run'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add' called from: /Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:70:in `_run_worker'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:55:in `_run'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
   -> 0.0327s
== 20170629134829 CreateFaeTextFields: migrated (0.0328s) =====================

== 20170629134830 CreateFaeChanges: migrating =================================
-- create_table(:fae_changes)
   -> 0.0013s
-- add_index(:fae_changes, :changeable_id)
   -> 0.0023s
-- add_index(:fae_changes, :changeable_type)
   -> 0.0033s
-- add_index(:fae_changes, :user_id)
   -> 0.0046s
== 20170629134830 CreateFaeChanges: migrated (0.0131s) ========================

        rake  fae:seed_db
E, [2017-06-29T15:58:25.347829 #19221] ERROR -- : fsevent: running worker failed: wrong number of arguments (given 2, expected 1):/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/base.rb:41:in `block (2 levels) in configure'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/rb-fsevent-0.10.1/lib/rb-fsevent/fsevent.rb:75:in `run'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:71:in `_run_worker'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:55:in `_run'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add' called from: /Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:70:in `_run_worker'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:55:in `_run'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/Users/romenigld/.rvm/gems/ruby-2.4.1@rails5.1/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
➜  fae git:(master) ✗
```

**Comment by jamesmk** [comment]
Hey @romenigld,

Re: the migration issue, we don't officially support Rails 5.1. We're working on it and I added a note in the Quickstart guide about it in #256.

The other issue looks like an issue with a Guard dependency that just popped up (https://github.com/guard/listen/issues/431). Guard isn't a Fae dependency, looks like there's a fix in the linked ticket.

thanks!
