### ISSUE TITLE
Incompatibility with Ruby 2.4

### ISSUE THREAD

**Issue by Spone** [wearefine/fae#276]
When I run a generator with Ruby 2.4, I get the following error:

```
bundle exec rails g fae:scaffold Product name description:text position:integer
Running via Spring preloader in process 25740
[WARNING] Could not load generator "generators/fae/scaffold_generator". Error: undefined method `expand_path' for Fae::File (call 'Fae::File.connection' to establish a connection):Class.
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fae-rails-1.5.1/lib/generators/fae/base_generator.rb:3:in `<class:BaseGenerator>'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fae-rails-1.5.1/lib/generators/fae/base_generator.rb:2:in `<module:Fae>'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fae-rails-1.5.1/lib/generators/fae/base_generator.rb:1:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fae-rails-1.5.1/lib/generators/fae/scaffold_generator.rb:1:in `require_relative'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fae-rails-1.5.1/lib/generators/fae/scaffold_generator.rb:1:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/command/behavior.rb:82:in `block (2 levels) in lookup'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/command/behavior.rb:78:in `each'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/command/behavior.rb:78:in `block in lookup'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/command/behavior.rb:77:in `each'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/command/behavior.rb:77:in `lookup'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/generators.rb:250:in `find_by_namespace'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/generators.rb:267:in `invoke'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/commands/generate/generate_command.rb:24:in `perform'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
/home/hans/projects/eleutheratahiti.com/bin/rails:9:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `block in load'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
Expected boolean default value for '--markerb'; got :erb (string)
Could not find generator 'fae:scaffold'. Maybe you meant 'css:scaffold', 'erb:scaffold' or 'scaffold'
Run `rails generate --help` for more options.
```

To make it compatible with Ruby 2.4, I think you need to replace [this line](https://github.com/wearefine/fae/blob/master/lib/generators/fae/scaffold_generator.rb#L4):

    source_root File.expand_path('../templates', __FILE__)

with

    source_root ::File.expand_path('../templates', __FILE__)

If you approve, I can prepare a PR with this change in all generators.

Let me know.

**Comment by jamesmk** [comment]
@Spone 👍 a PR would be awesome. Thanks!

**Comment by Spone** [comment]
Here is the PR: #282
