### ISSUE TITLE
Error when attempting `rake db:migrate` on v1.6 branch 

### ISSUE THREAD

**Issue by aaronransley** [wearefine/fae#292]
Am getting an `uninitialized constant AddSeoFieldsToRelease` error when trying to do a `rake db:migrate` from within the Fae dummy app on the v1.6 branch. My hunch says this is related to the recent work done for acronym formatting in admin form labels, but I'm not sure!

**Fix:** This is easily fixable by changing the class capitalization in the latest migration from `AddSEOFieldsToRelease` to `AddSeoFieldsToRelease`, but I didn't want to do so without first checking to see if this error has further reaching implications.

@jasonfine @jamesmk any ideas?

Full error:
```
-> % rake db:migrate
rails aborted!
NameError: uninitialized constant AddSeoFieldsToRelease
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:268:in `const_get'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:268:in `block in constantize'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `each'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `inject'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `constantize'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activesupport-5.0.2/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:961:in `load_migration'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:956:in `migration'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `disable_ddl_transaction'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1289:in `use_transaction?'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1219:in `rescue in execute_migration_in_transaction'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1208:in `execute_migration_in_transaction'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
NameError: uninitialized constant AddSeoFieldsToRelease
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:268:in `const_get'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:268:in `block in constantize'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `each'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `inject'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `constantize'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activesupport-5.0.2/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:961:in `load_migration'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:956:in `migration'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `disable_ddl_transaction'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1289:in `use_transaction?'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1281:in `ddl_transaction'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/aransley/.rvm/gems/ruby-2.3.2@fae/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by jamesmk** [comment]
@aaronransley Yeah, please rename the class `AddSEOFieldsToRelease` to `AddSeoFieldsToRelease`. Rails makes migrations classname assumptions from the filename, so they have to match the convention.

thanks!
