### ISSUE TITLE
ActionView::MissingTemplate when deleting image with Ajax

### ISSUE THREAD

**Issue by Spone** [wearefine/fae#309]
When I click on the little trash bin icon to delete an image, I get the JS confirmation popup, and when I confirm, nothing happens. Actually, the Ajax request goes through and deletes the image, but as there is an Internal Server Error (shown in the logs below) I don't get a visual confirmation of the deletion.

```
[76d46501-cfa1-42cf-92e0-649f10821cb4] Started DELETE "/admin/images/12/delete_image" for 92.154.88.74 at 2017-08-16 16:04:24 +0000
[76d46501-cfa1-42cf-92e0-649f10821cb4] Processing by Fae::ImagesController#delete_image as JS
[76d46501-cfa1-42cf-92e0-649f10821cb4]   Parameters: {"id"=>"12"}
[76d46501-cfa1-42cf-92e0-649f10821cb4]   Fae::User Load (1.8ms)  SELECT "fae_users".* FROM "fae_users" INNER JOIN "fae_roles" ON "fae_roles"."id" = "fae_users"."role_id" WHERE "fae_users"."active" = $1 AND "fae_roles"."name" = $2 ORDER BY "fae_users"."first_name" ASC, "fae_users"."last_name" ASC  [["active", "t"], ["name", "super admin"]]
[76d46501-cfa1-42cf-92e0-649f10821cb4]   Fae::User Load (1.5ms)  SELECT  "fae_users".* FROM "fae_users" WHERE "fae_users"."id" = $1 ORDER BY "fae_users"."first_name" ASC, "fae_users"."last_name" ASC LIMIT $2  [["id", 3], ["LIMIT", 1]]
[76d46501-cfa1-42cf-92e0-649f10821cb4]   Fae::Option Load (1.1ms)  SELECT  "fae_options".* FROM "fae_options" ORDER BY "fae_options"."id" ASC LIMIT $1  [["LIMIT", 1]]
[76d46501-cfa1-42cf-92e0-649f10821cb4]   Fae::Image Load (0.9ms)  SELECT  "fae_images".* FROM "fae_images" WHERE "fae_images"."id" = $1 LIMIT $2  [["id", 12], ["LIMIT", 1]]
[76d46501-cfa1-42cf-92e0-649f10821cb4]    (0.5ms)  BEGIN
[76d46501-cfa1-42cf-92e0-649f10821cb4]   Story Load (1.1ms)  SELECT  "stories".* FROM "stories" WHERE "stories"."id" = $1 ORDER BY "stories"."position" ASC LIMIT $2  [["id", 4], ["LIMIT", 1]]
[76d46501-cfa1-42cf-92e0-649f10821cb4]   Fae::Change Load (1.3ms)  SELECT  "fae_changes".* FROM "fae_changes" WHERE "fae_changes"."changeable_id" = $1 AND "fae_changes"."changeable_type" = $2 ORDER BY "fae_changes"."id" DESC LIMIT $3  [["changeable_id", 4], ["changeable_type", "Story"], ["LIMIT", 1]]
[76d46501-cfa1-42cf-92e0-649f10821cb4]   CACHE Fae::User Load (0.1ms)  SELECT  "fae_users".* FROM "fae_users" WHERE "fae_users"."id" = $1 ORDER BY "fae_users"."first_name" ASC, "fae_users"."last_name" ASC LIMIT $2  [["id", 3], ["LIMIT", 1]]
[76d46501-cfa1-42cf-92e0-649f10821cb4]   CACHE Story Load (0.1ms)  SELECT  "stories".* FROM "stories" WHERE "stories"."id" = $1 ORDER BY "stories"."position" ASC LIMIT $2  [["id", 4], ["LIMIT", 1]]
D, [2017-08-16T16:04:24.272759 #25063] DEBUG -- : [76d46501-cfa1-42cf-92e0-649f10821cb4]   SQL (1.2ms)  INSERT INTO "fae_changes" ("changeable_id", "changeable_type", "user_id", "change_type", "updated_attributes", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["changeable_id", 4], ["changeable_type", "Story"], ["user_id", 3], ["change_type", "updated"], ["updated_attributes", "---\n- cover_landscape\n"], ["created_at", "2017-08-16 16:04:24.267049"], ["updated_at", "2017-08-16 16:04:24.267049"]]
[76d46501-cfa1-42cf-92e0-649f10821cb4]    (4.6ms)  COMMIT
[76d46501-cfa1-42cf-92e0-649f10821cb4] Completed 500 Internal Server Error in 80ms (ActiveRecord: 14.3ms)
[76d46501-cfa1-42cf-92e0-649f10821cb4]   
[76d46501-cfa1-42cf-92e0-649f10821cb4] ActionView::MissingTemplate (Missing template fae/images/delete_image, fae/application/delete_image with {:locale=>[:en], :formats=>[:js, "application/ecmascript", "application/x-ecmascript", :html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :slim, :jbuilder]}. Searched in:
  * "/home/deploy/myapp/releases/20170816153326/app/views"
  * "/home/deploy/myapp/shared/bundle/ruby/2.4.0/gems/kaminari-0.17.0/app/views"
  * "/home/deploy/myapp/shared/bundle/ruby/2.4.0/bundler/gems/fae-fbf5cdb90b78/app/views"
  * "/home/deploy/myapp/shared/bundle/ruby/2.4.0/gems/devise-4.3.0/app/views"
):
[76d46501-cfa1-42cf-92e0-649f10821cb4]   
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionview (5.1.3) lib/action_view/path_set.rb:46:in `find'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionview (5.1.3) lib/action_view/lookup_context.rb:116:in `find'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionview (5.1.3) lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionview (5.1.3) lib/action_view/renderer/template_renderer.rb:38:in `determine_template'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionview (5.1.3) lib/action_view/renderer/template_renderer.rb:8:in `render'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionview (5.1.3) lib/action_view/renderer/renderer.rb:42:in `render_template'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionview (5.1.3) lib/action_view/renderer/renderer.rb:23:in `render'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionview (5.1.3) lib/action_view/rendering.rb:103:in `_render_template'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/streaming.rb:217:in `_render_template'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionview (5.1.3) lib/action_view/rendering.rb:83:in `render_to_body'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/abstract_controller/rendering.rb:24:in `render'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/rendering.rb:36:in `render'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activesupport (5.1.3) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
[76d46501-cfa1-42cf-92e0-649f10821cb4] /home/deploy/.rbenv/versions/2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activesupport (5.1.3) lib/active_support/core_ext/benchmark.rb:12:in `ms'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activerecord (5.1.3) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:43:in `render'
[76d46501-cfa1-42cf-92e0-649f10821cb4] remotipart (1.3.1) lib/remotipart/render_overrides.rb:16:in `render_with_remotipart'
[76d46501-cfa1-42cf-92e0-649f10821cb4] /home/deploy/myapp/shared/bundle/ruby/2.4.0/bundler/gems/fae-fbf5cdb90b78/app/controllers/fae/images_controller.rb:14:in `delete_image'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/abstract_controller/base.rb:186:in `process_action'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activesupport (5.1.3) lib/active_support/callbacks.rb:131:in `run_callbacks'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/rescue.rb:20:in `process_action'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activesupport (5.1.3) lib/active_support/notifications.rb:166:in `block in instrument'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activesupport (5.1.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activesupport (5.1.3) lib/active_support/notifications.rb:166:in `instrument'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activerecord (5.1.3) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/abstract_controller/base.rb:124:in `process'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionview (5.1.3) lib/action_view/rendering.rb:30:in `process'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal.rb:189:in `dispatch'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_controller/metal.rb:253:in `dispatch'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/routing/route_set.rb:31:in `serve'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/journey/router.rb:46:in `block in serve'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/journey/router.rb:33:in `each'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/journey/router.rb:33:in `serve'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/routing/route_set.rb:834:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] railties (5.1.3) lib/rails/engine.rb:522:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] railties (5.1.3) lib/rails/railtie.rb:185:in `public_send'
[76d46501-cfa1-42cf-92e0-649f10821cb4] railties (5.1.3) lib/rails/railtie.rb:185:in `method_missing'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/routing/mapper.rb:17:in `block in '
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/routing/mapper.rb:46:in `serve'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/journey/router.rb:46:in `block in serve'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/journey/router.rb:33:in `each'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/journey/router.rb:33:in `serve'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/routing/route_set.rb:834:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] warden (1.2.7) lib/warden/manager.rb:35:in `catch'
[76d46501-cfa1-42cf-92e0-649f10821cb4] warden (1.2.7) lib/warden/manager.rb:35:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] rack (2.0.3) lib/rack/etag.rb:25:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] rack (2.0.3) lib/rack/head.rb:12:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
[76d46501-cfa1-42cf-92e0-649f10821cb4] rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activesupport (5.1.3) lib/active_support/callbacks.rb:97:in `run_callbacks'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] railties (5.1.3) lib/rails/rack/logger.rb:36:in `call_app'
[76d46501-cfa1-42cf-92e0-649f10821cb4] railties (5.1.3) lib/rails/rack/logger.rb:24:in `block in call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activesupport (5.1.3) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activesupport (5.1.3) lib/active_support/tagged_logging.rb:26:in `tagged'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activesupport (5.1.3) lib/active_support/tagged_logging.rb:69:in `tagged'
[76d46501-cfa1-42cf-92e0-649f10821cb4] railties (5.1.3) lib/rails/rack/logger.rb:24:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/middleware/request_id.rb:25:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] rack (2.0.3) lib/rack/method_override.rb:22:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] rack (2.0.3) lib/rack/runtime.rb:22:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] activesupport (5.1.3) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] actionpack (5.1.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] railties (5.1.3) lib/rails/engine.rb:522:in `call'
[76d46501-cfa1-42cf-92e0-649f10821cb4] /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
[76d46501-cfa1-42cf-92e0-649f10821cb4] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
[76d46501-cfa1-42cf-92e0-649f10821cb4] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
[76d46501-cfa1-42cf-92e0-649f10821cb4] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
[76d46501-cfa1-42cf-92e0-649f10821cb4] /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by Spone** [comment]
This is related to `render :nothing => true` deprecation in Rails 5 (see https://github.com/rails/rails/pull/20336).

To make it work in Rails 5, this line:

    render :nothing => true

should be replaced by:

    head :ok

Here is a PR for this: #310
