### ISSUE TITLE
Unable to use with webpack only?

### ISSUE THREAD

**Issue by mooreds** [wearefine/fae#452]
Hi folks,

I create a brand new rails project:

`rails new project --webpack --skip-sprockets`

added fae-rails to the gemfile

`gem 'fae-rails'`

ran `bundle install`

tried to run `bundle exec rake db:create`

and got this error message:

```
j$ bundle exec rake db:create
rake aborted!
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x00000000049ddc40>
Did you mean?  asset_host
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/railtie/configuration.rb:97:in `method_missing'
/usr/share/rvm/gems/ruby-2.5.1/gems/fae-rails-2.0.0/config/initializers/assets.rb:1:in `<main>'
/usr/share/rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/usr/share/rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/usr/share/rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
/usr/share/rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/engine.rb:657:in `block in load_config_initializer'
/usr/share/rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/engine.rb:656:in `load_config_initializer'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/engine.rb:613:in `each'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/engine.rb:613:in `block in <class:Engine>'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
/home/vagrant/work/sampleproject/config/environment.rb:5:in `<main>'
/usr/share/rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/usr/share/rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/usr/share/rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
/usr/share/rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/usr/share/rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/usr/share/rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rvm/gems/ruby-2.5.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
/usr/share/rvm/gems/ruby-2.5.1/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/share/rvm/gems/ruby-2.5.1/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/usr/share/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:create => db:load_config => environment
(See full trace by running task with --trace)
```

I surmise that fae doesn't support webpack just yet, but wanted to confirm.

**Comment by mooreds** [comment]
Looks like if I run `rails new project --webpack` and keep sprockets, the admin interface works and I can still use webpack for my front end code.
